services:
  app:
    build: .
    environment:
      - DB_URL=${DB_URL}
      - DB_DIALECT=${DB_DIALECT}
    ports:
      - "4000:4000"
    command: python3 app.py
  test:
    build: .
    environment:
      - DB_URL=${DB_URL}
      - DB_DIALECT=${DB_DIALECT}
    command: pytest -s -v
