services:
  app:
    build: .
    env_file:
      - .env
    environment:
      - DB_URL=${DB_URL}
      - DB_DIALECT=${DB_DIALECT}
    ports:
      - "3001:3001"
    command: python3 app.py
  test:
    build: .
    env_file:
      - .env
    environment:
      - DB_URL=${DB_URL}
      - DB_DIALECT=${DB_DIALECT}
    ports:
      - "3001:3001"
    command: pytest -s -v
