name: Pytest CI

on:
  push:
    branches: [dev]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests container
        env:
          DB_DIALECT: ${{ secrets.DB_DIALECT }}
          DB_URL: ${{ secrets.DB_URL }}
        run: docker compose up test
